"""NHS_ChallengeA_Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127eTuPEwbxdLGtVcVkH8fUK6_5zNSRKZ

# ==========================================
# NHS STEP UP CHALLENGE A
# Antidepressant Prescribing Analysis
# Google Colab Version
# ==========================================

#1. Upload the dataset

#2. Import Libraries
"""

# Data manipulation
import pandas as pd
import numpy as np

# Visualisation
import matplotlib.pyplot as plt

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:,.2f}'.format)

"""#3. Import datasets"""

from google.colab import files

uploaded = files.upload()

# Load Excel file
df = pd.read_excel("Step Up Excel Data Dec 2024.xlsx")

# View first rows
df.head()

"""#Inspect The Data"""

# Dataset information
df.info()

# Dataset shape
print("Rows and columns:", df.shape)

# Check missing values
print(df.isnull().sum())

# View unique drugs
print("Unique drugs:", df['DRUG'].nunique())

# View unique regions
print("Unique regions:", df['REGIONAL_OFFICE_NAME'].nunique())

"""#5. Clean the Data"""

# Remove duplicates
df = df.drop_duplicates()

# Remove missing values
df = df.dropna()

# Ensure numeric columns are numeric
df['ITEMS'] = pd.to_numeric(df['ITEMS'], errors='coerce')
df['ACTUAL_COST'] = pd.to_numeric(df['ACTUAL_COST'], errors='coerce')

# Remove invalid rows
df = df.dropna(subset=['ITEMS', 'ACTUAL_COST'])

# Final check
df.info()

"""#NHS Colour Scheme"""

# NHS Colour Palette
nhs_blue = '#005EB8'
nhs_dark_blue = '#003087'
nhs_light_blue = '#41B6E6'
nhs_aqua = '#00A9CE'
nhs_grey = '#768692'

"""##Make charts look professional"""

plt.style.use('ggplot')

"""#Exercise 1: Aggregating Data

The guide asks you to calculate top prescribed antidepressants, national costs, regional spend, and total prescribed items.

##Q1. Top 10 prescribed antidepressants nationally
"""

top_10_drugs = (
    df.groupby('DRUG')['ITEMS']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_10_drugs

"""##Q2. National cost of Mirtazapine"""

mirtazapine_cost = (
    df[df['DRUG'].str.contains('Mirtazapine', case=False, na=False)]
    ['ACTUAL_COST']
    .sum()
)

print("National Mirtazapine Cost: £{:,.2f}".format(mirtazapine_cost))

"""##Q3. Spend of Sertraline hydrochloride in the Midlands"""

midlands_sertraline = df[
    (df['REGIONAL_OFFICE_NAME'].str.contains('Midlands', case=False, na=False)) &
    (df['DRUG'].str.contains('Sertraline', case=False, na=False))
]

midlands_sertraline_cost = midlands_sertraline['ACTUAL_COST'].sum()

print("Midlands Sertraline Cost: £{:,.2f}".format(midlands_sertraline_cost))

"""##Q4. Total antidepressant items prescribed nationally"""

total_items = df['ITEMS'].sum()

print("Total National Antidepressant Items:", format(total_items, ','))

"""#Exercise 2: Visualising Data

The guide asks you to create charts comparing prescribed items, prescribing costs, and regional differences.

##Chart 1. Top 5 most prescribed drugs
"""

top_5 = (
    df.groupby('DRUG')['ITEMS']
    .sum()
    .sort_values(ascending=True)
    .tail(5)
)

plt.figure(figsize=(10,6))

plt.barh(top_5.index, top_5.values, color=nhs_blue)

plt.title('Top 5 Most Prescribed Antidepressants', fontsize=16, fontweight='bold')
plt.xlabel('Items Prescribed')
plt.ylabel('Drug')

for index, value in enumerate(top_5.values):
    plt.text(value, index, f'{value:,.0f}', va='center')

plt.tight_layout()
plt.show()

"""##Chart 2. Sertraline cost in the North East"""

import textwrap

wrapped_labels = [
    '\n'.join(textwrap.wrap(label, 15))
    for label in sertraline_cost_by_icb.index
]

plt.figure(figsize=(10,5))

plt.bar(
    wrapped_labels,
    sertraline_cost_by_icb.values,
    color=nhs_dark_blue
)

plt.title(
    'Sertraline Prescribing Cost in North East',
    fontsize=16,
    fontweight='bold'
)

plt.xlabel('ICB')
plt.ylabel('Cost (£)')

plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

"""##Chart 3A. Total items by antidepressant"""

items_by_drug = (
    df.groupby('DRUG')['ITEMS']
    .sum()
    .sort_values(ascending=False)
)

plt.figure(figsize=(14,6))

plt.bar(
    items_by_drug.index,
    items_by_drug.values,
    color=nhs_blue
)

plt.title('Total Antidepressant Prescribing Items by Drug', fontsize=16, fontweight='bold')
plt.xlabel('Drug')
plt.ylabel('Items Prescribed (million)')

plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

"""##Chart 3B. Total cost by antidepressant"""

cost_by_drug = (
    df.groupby('DRUG')['ACTUAL_COST']
    .sum()
    .sort_values(ascending=False)
)

plt.figure(figsize=(14,6))

plt.bar(
    cost_by_drug.index,
    cost_by_drug.values,
    color=nhs_aqua
)

plt.title('Total Antidepressant Prescribing Cost by Drug', fontsize=16, fontweight='bold')
plt.xlabel('Drug')
plt.ylabel('Cost (£ million)')

plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

"""##Chart 4A. Top 10 drugs by prescribed items"""

top_10_items = (
    df.groupby('DRUG')['ITEMS']
    .sum()
    .sort_values(ascending=True)
    .tail(10)
)

plt.figure(figsize=(10,7))

plt.barh(
    top_10_items.index,
    top_10_items.values,
    color=nhs_blue
)

plt.title('Top 10 Antidepressants by Prescribed Items', fontsize=16, fontweight='bold')
plt.xlabel('Items Prescribed (million)')
plt.ylabel('Drug')

for index, value in enumerate(top_10_items.values):
    plt.text(value, index, f'{value:,.0f}', va='center')

plt.tight_layout()
plt.show()

"""##Chart 4B. Top 10 drugs by prescribing cost"""

top_10_cost = (
    df.groupby('DRUG')['ACTUAL_COST']
    .sum()
    .sort_values(ascending=True)
    .tail(10)
)

plt.figure(figsize=(10,7))

plt.barh(
    top_10_cost.index,
    top_10_cost.values,
    color=nhs_aqua
)

plt.title('Top 10 Antidepressants by Prescribing Cost', fontsize=16, fontweight='bold')
plt.xlabel('Cost (£ million)')
plt.ylabel('Drug')

for index, value in enumerate(top_10_cost.values):
    plt.text(value, index, f'£{value:,.0f}', va='center')

plt.tight_layout()
plt.show()

"""#Exercise 3: Pivot Tables

The guide asks for pivot tables comparing regional prescribing items and cost.

##Pivot 1. Total prescribing items by region
"""

pivot_items = pd.pivot_table(
    df,
    values='ITEMS',
    index='REGIONAL_OFFICE_NAME',
    aggfunc='sum'
)

pivot_items = pivot_items.sort_values(by='ITEMS', ascending=False)

pivot_items

"""##Pivot 2. Total prescribing cost by region"""

pivot_cost = pd.pivot_table(
    df,
    values='ACTUAL_COST',
    index='REGIONAL_OFFICE_NAME',
    aggfunc='sum'
)

pivot_cost = pivot_cost.sort_values(by='ACTUAL_COST', ascending=False)

pivot_cost

"""##Regional comparison charts

### Items by region
"""

plt.figure(figsize=(10,6))

plt.barh(
    pivot_items.index,
    pivot_items['ITEMS'],
    color=nhs_light_blue
)

plt.title('Total Antidepressant Prescribing Items by Region', fontsize=16, fontweight='bold')
plt.xlabel('Items Prescribed (Million)')
plt.ylabel('Region')

plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

"""###Cost by region"""

plt.figure(figsize=(10,6))

plt.barh(
    pivot_cost.index,
    pivot_cost['ACTUAL_COST'],
    color=nhs_dark_blue
)

plt.title('Total Antidepressant Prescribing Cost by Region', fontsize=16, fontweight='bold')
plt.xlabel('Cost (£ Million)')
plt.ylabel('Region')

plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

"""##Generate useful insight statements"""

highest_items_drug = items_by_drug.idxmax()
highest_items_value = items_by_drug.max()

highest_cost_drug = cost_by_drug.idxmax()
highest_cost_value = cost_by_drug.max()

highest_items_region = pivot_items['ITEMS'].idxmax()
highest_items_region_value = pivot_items['ITEMS'].max()

highest_cost_region = pivot_cost['ACTUAL_COST'].idxmax()
highest_cost_region_value = pivot_cost['ACTUAL_COST'].max()

print(f"The most prescribed antidepressant nationally was {highest_items_drug}, with {highest_items_value:,.0f} items prescribed.")

print(f"The antidepressant with the highest prescribing cost was {highest_cost_drug}, costing £{highest_cost_value:,.2f}.")

print(f"The region with the highest prescribing volume was {highest_items_region}, with {highest_items_region_value:,.0f} items.")

print(f"The region with the highest prescribing cost was {highest_cost_region}, costing £{highest_cost_region_value:,.2f}.")
